randomize()
DefaultPlaylist = ds_list_create()

ds_list_add(DefaultPlaylist, Track_1_Bipolar_Bear)
ds_list_add(DefaultPlaylist, Track_2_Klungos_Arcade)
ds_list_add(DefaultPlaylist, Track_3_Duty_Cycle_GB)
ds_list_add(DefaultPlaylist, Track_4_Boss_Ass_Bits)
ds_list_add(DefaultPlaylist, Track_5_Quantum_Leaper)
ds_list_add(DefaultPlaylist, Track_6_BOMB)
ds_list_add(DefaultPlaylist, Track_7_Waves)
ds_list_add(DefaultPlaylist, Track_8_Equinoxes)
ds_list_add(DefaultPlaylist, Track_10_Flamingo)
ds_list_add(DefaultPlaylist, Track_11_Digital_Dream)
ds_list_add(DefaultPlaylist, Track_12_Wizard_House)
ds_list_add(DefaultPlaylist, Track_13_Graveyard_Shift)
ds_list_add(DefaultPlaylist, Track_14_Beast_Mode)
ds_list_add(DefaultPlaylist, Track_15_Reckless)
ds_list_add(DefaultPlaylist, Track_16_Wake_the_Fuck_Up)
ds_list_add(DefaultPlaylist, Track_17_Final_Sector)
ds_list_add(DefaultPlaylist, Track_18_Popcorn_Blast)
ds_list_add(DefaultPlaylist, Track_19_Superbyte)
ds_list_add(DefaultPlaylist, Track_20_Eat_My_Chips)
ds_list_add(DefaultPlaylist, Track_21_Expedition)
ds_list_add(DefaultPlaylist, Track_22_Catnip)
ds_list_add(DefaultPlaylist, Track_23_Rainbow_Ride)
ds_list_add(DefaultPlaylist, Track_24_Journey)
ds_list_add(DefaultPlaylist, Track_25_Summer_Wars)
ds_list_add(DefaultPlaylist, Track_26_World_10)

Current_Track = 24 //irandom(25)
audio_stop_all()
TrackPlaying = ds_list_find_value(DefaultPlaylist, Current_Track)
audio_play_sound(TrackPlaying, 0, false)